### ISSUE TITLE
Raises UndefinedFunctionError for Macro.pipe_warning/1 in 1.6

### ISSUE THREAD

**Issue by paradox460** [taiansu/pipe_to#3]
When attempting to use this library, error messages are raised whenever any "enhanced" pipes are called:

```
** (UndefinedFunctionError) function Macro.pipe_warning/1 is undefined or private. Did you mean one of:

      * pipe/3

    (elixir) Macro.pipe_warning({{:., [line: 2], [{:__aliases__, [line: 2], [:Enum]}, :at]}, [line: 2], [[1, 2, 3]]})
    (pipe_to) lib/pipe_to.ex:31: anonymous fn/3 in PipeTo."MACRO-~>"/3
    (stdlib) lists.erl:1263: :lists.foldl/3
    (pipe_to) expanding macro: PipeTo.~>/2
    iex:2: (file)
```

Looking through the elixir source code, it appears that the `pipe_warning/1` function was deleted in [this](https://github.com/elixir-lang/elixir/commit/a1d6d4cd910826834a2a06cdb3a6a7914bf663f3) commit, in Aug 21 of last year.

**Comment by taiansu** [comment]
Thanks for the report, will fix it these couple days. ❤️
